@echo off
echo Starting Research Paper Analysis Agent...
echo.
echo Checking Python environment...
python --version
echo.
echo Installing/updating dependencies...
pip install -r requirements.txt
echo.
echo Starting Streamlit application...
streamlit run app.py
pause
